/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Manrope', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      colors: {
        'outline-variant': '#aaaeb0',
        'on-tertiary-container': '#583400',
        'on-primary': '#ccffd8',
        outline: '#737779',
        'on-error': '#ffefee',
        tertiary: '#835000',
        secondary: '#515c6f',
        'secondary-fixed': '#d8e3fa',
        'surface-container-highest': '#d8dee1',
        'on-primary-fixed-variant': '#006c3c',
        'on-secondary-container': '#475265',
        'primary-fixed-dim': '#8aebac',
        'on-secondary-fixed-variant': '#515c6f',
        'on-secondary': '#eef2ff',
        'tertiary-fixed': '#fcb259',
        primary: {
          DEFAULT: '#006a3b',
          50: '#f0fdf4',
          100: '#dcfce7',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
        },
        'tertiary-container': '#fcb259',
        'on-error-container': '#570008',
        error: '#b31b25',
        'on-surface-variant': '#585c5e',
        'surface-tint': '#006a3b',
        'inverse-primary': '#98fab9',
        'error-container': '#fb5151',
        'tertiary-fixed-dim': '#eca54d',
        background: '#f4f7f9',
        'secondary-dim': '#455063',
        'on-tertiary': '#fff0e4',
        'primary-dim': '#005c33',
        'surface-container': '#e4e9eb',
        'primary-fixed': '#98fab9',
        'surface-container-low': '#edf1f3',
        'primary-container': '#98fab9',
        'error-dim': '#9f0519',
        'surface-container-high': '#dee3e6',
        'secondary-container': '#d8e3fa',
        'surface-container-lowest': '#ffffff',
        'on-primary-container': '#006035',
        'on-tertiary-fixed': '#3c2200',
        'inverse-surface': '#0b0f10',
        surface: '#f4f7f9',
        'secondary-fixed-dim': '#cad5ec',
        'surface-bright': '#f4f7f9',
        'on-surface': '#2b2f31',
        'tertiary-dim': '#734500',
        'on-background': '#2b2f31',
        'inverse-on-surface': '#9a9d9f',
        'surface-variant': '#d8dee1',
        'on-secondary-fixed': '#354052',
        'on-primary-fixed': '#004c29',
        'surface-dim': '#cfd5d8',
        'on-tertiary-fixed-variant': '#653c00',
        'background-light': '#f8f6f6',
        'background-dark': '#221610',
        'gro-green': '#2e8b57',
        'gro-orange': '#f37021',
      },
      borderRadius: {
        '2xl': '1rem',
      },
    },
  },
  plugins: [],
}
